// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered tool suggestion based on the content that the user is currently viewing.
 *
 * - suggestTools - A function that suggests relevant Bangla tools based on the content.
 * - SuggestToolsInput - The input type for the suggestTools function.
 * - SuggestToolsOutput - The return type for the suggestTools function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestToolsInputSchema = z.object({
  content: z.string().describe('The content the user is currently viewing.'),
});
export type SuggestToolsInput = z.infer<typeof SuggestToolsInputSchema>;

const SuggestToolsOutputSchema = z.object({
  tools: z.array(z.string()).describe('An array of suggested tool names.'),
});
export type SuggestToolsOutput = z.infer<typeof SuggestToolsOutputSchema>;

export async function suggestTools(input: SuggestToolsInput): Promise<SuggestToolsOutput> {
  return suggestToolsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestToolsPrompt',
  input: {schema: SuggestToolsInputSchema},
  output: {schema: SuggestToolsOutputSchema},
  prompt: `You are an AI assistant that suggests relevant Bangla tools based on the content the user is currently viewing.

  Suggest a list of tools that would be helpful to the user based on the following content:

  Content: {{{content}}}

  Return only the tool names in an array.
  `,
});

const suggestToolsFlow = ai.defineFlow(
  {
    name: 'suggestToolsFlow',
    inputSchema: SuggestToolsInputSchema,
    outputSchema: SuggestToolsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
